import numpy as np
# Since each survey asks different Questions, I wanted to make it easy to get the unique Questions and categories them
# Get Every Unique Header for Question 1-22

dfHeaders = np.array(["record - Record number", "Age", "Gender", "Age Range",
             "State", "Region",	"Employment Status",
             "Ethnicity", "HasChildren", "Children under 4", "Children 5to9",
             "Children 10to13", "Children 14to18", "Children 19to25", "Children 26Up",
             "Children Unknown", "HouseholdIncome",	"HasFlatPanelTelevision",
             "HasDVR", "HasStreamingBox", "HasThumbdrive", "HasBluRay",
             "HasGamingConsole", "HasPortableGamingConsole", "HasWirelessRouter",
             "HasDesktop", "HasLaptop", "HasLaptopHybrid", "HasLargeTablet",
             "HasSmallTablet", "HasEReader", "HasSmallSmartphone", "HasLargeSmartphone",
             "HasBasicPhone", "HasSmartWatch", "HasFitnessBand", "HasSmartGlasses",
             "Has3dPrinter", "HasNoDevices", "HasUnknownDevices",
             "PurchaseFlatPanelTelevision", "PurchaseDVR", "PurchaseStreamingBox", "PurchaseThumbdrive",
             "PurchaseBluRay", "PurchaseGamingConsole", "PurchasePortableGamingConsole", "PurchaseWirelessRouter",
             "PurchaseDesktop", "PurchaseLaptop", "PurchaseLaptopHybrid",
             "PurchaseLargeTablet", "PurchaseSmallTablet", "PurchaseEReader",
             "PurchaseSmallSmartphone", "PurchaseLargeSmartphone", "PurchaseBasicPhone",
             "PurchaseSmartWatch", "PurchaseFitnessBand", "PurchaseSmartGlasses",
             "Purchase3DPrinter", "PurchaseNone", "PurchaseUnknown",
             "ValueFlatPanelTelevision", "ValueDVR", "ValueStreamingBox",
             "ValueThumbDrive", "ValueBlueRay", "ValueGamingConsole",
             "ValuePortableGamingConsole", "ValueNetworkRouter", "ValueDesktop",
             "ValueLaptop", "ValueLaptopHybrid", "ValueLargeTablet",
             "ValueSmallTablet", "ValueEReader", "ValueSmallSmartphone",
             "ValueLargeSmartphone", "ValueBasicPhone", "ValueSmartWatch",
             "ValueFitnessBand", "ValueSmartGlasses", "Value3DPrinter",
             "ValuePlaceHolder", "TimeWatchingMoviesSmartphone", "TimeWatchingMoviesTablet",
             "TimeWatchingMoviesPC", "TimeWatchingMoviesTV", "TimeWatchingSportsSmartphone",
             "TimeWatchingSportsTablet", "TimeWatchingSportsPC", "TimeWatchingSportsTV",
             "TimeWatchingTvSmartphone", "TimeWatchingTvTablet", "TimeWatchingTvPC",
             "TimeWatchingTvTV", "FrequentApp-Photo","FrequentApp-Banking",
             "FrequentApp-Health", "FrequentApp-Food", "FrequentApp-Retail",
             "FrequentApp-Navigation", "FrequentApp-SocialMedia", "FrequentApp-Books",
             "FrequentApp-Music", "FrequentApp-VideoStreaming", "FrequentApp-Reviews",
             "FrequentApp-News", "FrequentApp-Newspaper", "FrequentApp-Magazines",
             "FrequentApp-Utilities", "FrequentApp-QRReader", "FrequentApp-Travel",
             "FrequentApp-Transport", "FrequentApp-Location", "FrequentApp-Language",
             "FrequentApp-Movie", "FrequentApp-Business", "FrequentApp-Games",
             "FrequentApp-Productivity", "FrequentApp-Sports", "FrequentApp-Weather",
             "FrequentApp-Browser", "FrequentApp-VOIP", "FrequentApp-None",
             "FrequentApp-Unknown",
             "record - Record number", "Age", "Gender",	"Age Range",
             "State", "Region",	"Employment Status", "Ethnicity",
             "HasChildren",	"Children under 4",	"Children 5to9", "Children 10to13", "Children 14to18",
             "Children 19to25",	"Children 26Up", "Children Unknown", "HouseholdIncome",
             "HasFlatPanelTelevision", "HasDVR", "HasStreamingBox", "HasPortableStreaming", "HasOverAirDigitalTV",
             "HasBluRay", "HasGamingConsole", "HasPortableGamingConsole", "HasWirelessRouter",
             "HasDesktop", "HasLaptop", "HasTablet", "HasEReader", "HasSmartPhone",
             "HasBasicPhone", "HasSmartWatch", "HasFitnessBand", "HasVRHeadSet",
             "HasDrone", "HasNoDevices", "HasUnknownDevices", "PurchaseFlatPanelTelevision",
             "PurchaseDVR", "PurchaseStreamingBox", "PurchaseThumbdrive", "PurchaseOverAirDigitalTV",
             "PurchaseBluRay", "PurchaseGamingConsole", "PurchasePortableGamingConsole", "PurchaseWirelessRouter",
             "PurchaseDesktop", "PurchaseLaptop", "PurchaseTablet", "PurchaseEReader", "PurchaseSmartPhone",
             "PurchaseBasicPhone", "PurchaseSmartWatch", "PurchaseFitnessBand", "PurchaseVRHeadset",
             "PurchaseDrone", "PurchaseNoDevices", "PurchaseUnkown", "ValueFlatPanelTelevision",
             "ValueDVR", "ValueStreamingBox", "ValueThumbDrive", "ValueOverAirTV",
             "ValueBlueRay", "ValueGamingConsole", "ValuePortableGamingConsole", "ValueNetworkRouter",
             "ValueDesktop", "ValueLaptop", "ValueTablet", "ValueEReader",
             "ValueSmartPhone", "ValueBasicPhone", "ValueSmartWatch", "ValueFitnessBand",
             "ValueVRHeadset", "ValueDrone", "ValuePlaceholder", "TimeWatchingMoviesSmartphone",
             "TimeWatchingMoviesTablet", "TimeWatchingMoviesPC", "TimeWatchingMoviesTV", "TimeWatchingSportsSmartphone",
             "TimeWatchingSportsTablet", "TimeWatchingSportsPC", "TimeWatchingSportsTV", "TimeWatchingTvSmartphone",
             "TimeWatchingTvTablet", "TimeWatchingTvPC", "TimeWatchingTvTV", "FrequentApp-Photo",
             "FrequentApp-Banking", "FrequentApp-Health", "FrequentApp-Food", "FrequentApp-Retail",
             "FrequentApp-Navigation", "FrequentApp-SocialMedia", "FrequentApp-Books", "FrequentApp-Music",
             "FrequentApp-VideoStreaming", "FrequentApp-Reviews", "FrequentApp-News", "FrequentApp-Newspaper",
             "FrequentApp-Magazines", "FrequentApp-Utilities", "FrequentApp-QRReader", "FrequentApp-Travel",
             "FrequentApp-Transport", "FrequentApp-Location", "FrequentApp-Language", "FrequentApp-Movie",
             "FrequentApp-Business", "FrequentApp-Games", "FrequentApp-Productivity", "FrequentApp-Sports",
             "FrequentApp-Weather", "FrequentApp-Browser", "FrequentApp-VOIP", "FrequentApp-Dating", "FrequentApp-Messaging",
             "FrequentApp-VOIP", "FrequentApp-Education", "FrequentApp-Tickets", "FrequentApp-Reservations",
             "FrequentApp-Hobbies", "FrequentApp-None", "FrequentApp-Unknown"])


uniqueQuestions = np.unique(dfHeaders)

uniqueQuestions.sort()

print(list(uniqueQuestions))
